on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Get user profile URL
        id: user_profile_url
        run: |
          pr_number=${{ github.event.number }}
          echo ${pr_number}
          pr_url = "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number"
          echo ${pr_url}
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${pr_url})
          user_url=$(echo "$response" | jq -r '.user.url')
          echo ${response}
          echo "user_profile_url=${user_url}" >> $GITHUB_OUTPUT
          
      - run: |
          echo ${{ steps.user_profile_url.outputs.user_profile_url }}
