on: pull_request

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Get user profile URL
        id: user_profile_url
        run: |
          pr_number=${{ github.event.number }}
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}")
          user_url=$(echo "$response" | jq -r '.user.url')
          echo "::set-output name=user_profile_url::$user_url"
          
      - run: |
          echo ${{ user_profile_url.user_profile_url }}
